language: ruby
rvm:
  - "2.1.2"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
