development:
  adapter: postgresql
  encoding: utf8
  database: pwtinvest_development
  username: marcelo_reichert

test:
  adapter: postgresql
  encoding: utf8
  database: pwtinvest_test
  pool: 5
  username: marcelo_reichert
